export type Transaction = {
  id: string;
  transaction_number: string;
  date: string;
  donor_id: string;
  donor_name?: string;
  donor_email?: string;
  received: number;
  base_amount?: number;
  processing_fee?: number;
  gross_amount?: number;
  net_amount?: number;
  type: "DONATION" | "REFUND" | "TRANSFER" | "OTHER";
  donation_type?: "one_time" | "recurring";
  status: "COMPLETE" | "FAILED" | "PENDING" | "CANCELLED";
  recipient_id: string;
  recipient_name?: string;
  mission_agency_name?: string | null;
  payment_method?: string;
  notes?: string;
  designation?: string | null;
  created_at: string;
  updated_at?: string;
  stripe_payment_intent_id?: string;
  stripe_subscription_id?: string;
  stripe_invoice_id?: string;
  receipt_id?: string;
  receipt_sent_at?: string;
};
