


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."bump_amen_count"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  if tg_op = 'INSERT' then
    update public.prayers set amen_count = amen_count + 1, updated_at = now()
    where id = new.prayer_id;
  elsif tg_op = 'DELETE' then
    update public.prayers set amen_count = greatest(amen_count - 1,0), updated_at = now()
    where id = old.prayer_id;
  end if;
  return null;
end$$;


ALTER FUNCTION "public"."bump_amen_count"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."bump_update_count"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  if tg_op = 'INSERT' then
    update public.prayers set update_count = update_count + 1, updated_at = now()
    where id = new.prayer_id;
  elsif tg_op = 'DELETE' then
    update public.prayers set update_count = greatest(update_count - 1,0), updated_at = now()
    where id = old.prayer_id;
  end if;
  return null;
end$$;


ALTER FUNCTION "public"."bump_update_count"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public', 'auth'
    AS $$declare
  provider text;
begin


  return new;
end;$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_admin"() RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.users
    WHERE user_id = auth.uid()
    AND role = 1
  );
END;
$$;


ALTER FUNCTION "public"."is_admin"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."set_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  new.updated_at := now();
  return new;
end$$;


ALTER FUNCTION "public"."set_updated_at"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."agencies" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" character varying NOT NULL,
    "contact_user_id" "uuid",
    "email" "text",
    "phone_number" character varying,
    "address" "text",
    "city" character varying,
    "country" character varying,
    "website" "text"
);


ALTER TABLE "public"."agencies" OWNER TO "postgres";


ALTER TABLE "public"."agencies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."agencies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."churches" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" character varying NOT NULL,
    "contact_user_id" "uuid",
    "phone_number" character varying,
    "address" "text",
    "city" character varying,
    "country" character varying,
    "website" "text"
);


ALTER TABLE "public"."churches" OWNER TO "postgres";


ALTER TABLE "public"."churches" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."churches_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."colleges" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" character varying NOT NULL,
    "contact_user_id" "uuid",
    "email" "text",
    "phone_number" character varying,
    "address" "text",
    "city" character varying,
    "country" character varying,
    "website" "text"
);


ALTER TABLE "public"."colleges" OWNER TO "postgres";


ALTER TABLE "public"."colleges" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."colleges_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."donors" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "user_id" "uuid",
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "email" "text",
    "phone_number" "text",
    "country" "text",
    "city" "text",
    "address" "text",
    "postal_code" "text",
    "organization_name" "text",
    "donation_preference" "text",
    "total_donated" numeric(12,2) DEFAULT 0,
    "is_active" boolean DEFAULT true,
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."donors" OWNER TO "postgres";


ALTER TABLE "public"."donors" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."donors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."missionaries" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "first_name" character varying NOT NULL,
    "last_name" character varying NOT NULL,
    "email" "text",
    "phone_number" character varying,
    "country_of_residence" character varying,
    "destination_country" character varying,
    "mission_status" character varying,
    "open_to_visits" boolean DEFAULT false,
    "user_id" "uuid",
    "agency_id" bigint,
    "sending_church_id" bigint,
    "mission_field_church_id" bigint,
    "college_id" bigint,
    "biography" "text",
    CONSTRAINT "missionaries_mission_status_check" CHECK ((("mission_status")::"text" = ANY ((ARRAY['On-Field'::character varying, 'Furlough'::character varying, 'Deputation'::character varying])::"text"[])))
);


ALTER TABLE "public"."missionaries" OWNER TO "postgres";


ALTER TABLE "public"."missionaries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."missionaries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."page_approvals" (
    "id" bigint NOT NULL,
    "page_id" bigint NOT NULL,
    "requested_by" "uuid",
    "approved_by" "uuid",
    "status" "text" DEFAULT 'Pending'::"text",
    "reviewed_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "page_approvals_status_check" CHECK (("status" = ANY (ARRAY['Pending'::"text", 'Agency Approved'::"text", 'Published'::"text", 'Unpublished'::"text"])))
);


ALTER TABLE "public"."page_approvals" OWNER TO "postgres";


ALTER TABLE "public"."page_approvals" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."page_approvals_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."page_donations" (
    "id" bigint NOT NULL,
    "donor_id" bigint,
    "page_id" bigint NOT NULL,
    "amount" numeric(12,2) NOT NULL,
    "currency" "text" DEFAULT 'USD'::"text",
    "transaction_ref" "text",
    "status" "text" DEFAULT 'Pending'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "page_donations_status_check" CHECK (("status" = ANY (ARRAY['Pending'::"text", 'Complete'::"text", 'Failed'::"text"])))
);


ALTER TABLE "public"."page_donations" OWNER TO "postgres";


ALTER TABLE "public"."page_donations" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."page_donations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."page_media" (
    "id" bigint NOT NULL,
    "page_id" bigint NOT NULL,
    "media_type" "text",
    "media_url" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone,
    "description" "text",
    "views" integer,
    "reactions" integer,
    "thumbnail_url" "text",
    CONSTRAINT "page_media_media_type_check" CHECK (("media_type" = ANY (ARRAY['image'::"text", 'video'::"text"])))
);


ALTER TABLE "public"."page_media" OWNER TO "postgres";


ALTER TABLE "public"."page_media" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."page_media_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."page_widgets" (
    "id" bigint NOT NULL,
    "page_id" bigint NOT NULL,
    "widget_type" "text",
    "widget_title" "text",
    "widget_data" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."page_widgets" OWNER TO "postgres";


ALTER TABLE "public"."page_widgets" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."page_widgets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pages" (
    "id" bigint NOT NULL,
    "organization_type" "text" NOT NULL,
    "organization_id" bigint NOT NULL,
    "page_url" "text",
    "profile_photo_url" "text",
    "banner_photo_url" "text",
    "short_quote" "text",
    "about_text" "text",
    "intro_text" "text",
    "is_published" boolean DEFAULT false,
    "published_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "pages_organization_type_check" CHECK (("organization_type" = ANY (ARRAY['church'::"text", 'college'::"text", 'agency'::"text", 'missionary'::"text", 'donor'::"text"])))
);


ALTER TABLE "public"."pages" OWNER TO "postgres";


ALTER TABLE "public"."pages" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."pages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."prayer_reactions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "prayer_id" bigint NOT NULL,
    "type" "text" DEFAULT 'amen'::"text" NOT NULL,
    CONSTRAINT "prayer_reactions_type_check" CHECK (("type" = 'amen'::"text"))
);


ALTER TABLE "public"."prayer_reactions" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."prayer_reactions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."prayer_reactions_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."prayer_reactions_id_seq" OWNED BY "public"."prayer_reactions"."id";



CREATE TABLE IF NOT EXISTS "public"."prayer_updates" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "prayer_id" bigint NOT NULL,
    "body" "text" NOT NULL
);


ALTER TABLE "public"."prayer_updates" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."prayer_updates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."prayer_updates_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."prayer_updates_id_seq" OWNED BY "public"."prayer_updates"."id";



CREATE TABLE IF NOT EXISTS "public"."prayers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "deleted_at" timestamp with time zone,
    "user_id" "uuid" NOT NULL,
    "page_id" bigint,
    "title" "text",
    "body" "text" NOT NULL,
    "is_published" boolean DEFAULT true NOT NULL,
    "visibility" "text" DEFAULT 'public'::"text" NOT NULL,
    "amen_count" integer DEFAULT 0 NOT NULL,
    "update_count" integer DEFAULT 0 NOT NULL,
    "share_count" integer DEFAULT 0 NOT NULL,
    CONSTRAINT "prayers_visibility_check" CHECK (("visibility" = ANY (ARRAY['public'::"text", 'private'::"text", 'supporters'::"text"])))
);


ALTER TABLE "public"."prayers" OWNER TO "postgres";


COMMENT ON TABLE "public"."prayers" IS 'User-created prayer requests connected to auth.users.';



CREATE SEQUENCE IF NOT EXISTS "public"."prayers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."prayers_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."prayers_id_seq" OWNED BY "public"."prayers"."id";



CREATE TABLE IF NOT EXISTS "public"."user_roles" (
    "id" bigint NOT NULL,
    "role" character varying
);


ALTER TABLE "public"."user_roles" OWNER TO "postgres";


ALTER TABLE "public"."user_roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "role" smallint,
    "status" character varying DEFAULT 'Pending'::character varying,
    "first_name" character varying,
    "last_name" character varying,
    "email" "text" NOT NULL,
    "last_activity" timestamp with time zone
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."prayer_reactions" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."prayer_reactions_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."prayer_updates" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."prayer_updates_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."prayers" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."prayers_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."agencies"
    ADD CONSTRAINT "agencies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."churches"
    ADD CONSTRAINT "churches_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."colleges"
    ADD CONSTRAINT "colleges_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."donors"
    ADD CONSTRAINT "donors_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."donors"
    ADD CONSTRAINT "donors_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."missionaries"
    ADD CONSTRAINT "missionaries_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."missionaries"
    ADD CONSTRAINT "missionaries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."page_approvals"
    ADD CONSTRAINT "page_approvals_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."page_donations"
    ADD CONSTRAINT "page_donations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."page_media"
    ADD CONSTRAINT "page_media_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."page_widgets"
    ADD CONSTRAINT "page_widgets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pages"
    ADD CONSTRAINT "pages_org_unique" UNIQUE ("organization_type", "organization_id");



ALTER TABLE ONLY "public"."pages"
    ADD CONSTRAINT "pages_page_url_key" UNIQUE ("page_url");



ALTER TABLE ONLY "public"."pages"
    ADD CONSTRAINT "pages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."prayer_reactions"
    ADD CONSTRAINT "prayer_reactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."prayer_reactions"
    ADD CONSTRAINT "prayer_reactions_user_id_prayer_id_type_key" UNIQUE ("user_id", "prayer_id", "type");



ALTER TABLE ONLY "public"."prayer_updates"
    ADD CONSTRAINT "prayer_updates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."prayers"
    ADD CONSTRAINT "prayers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_donors_email" ON "public"."donors" USING "btree" ("email");



CREATE INDEX "idx_donors_is_active" ON "public"."donors" USING "btree" ("is_active");



CREATE INDEX "idx_donors_user_id" ON "public"."donors" USING "btree" ("user_id");



CREATE INDEX "idx_page_approvals_page_id" ON "public"."page_approvals" USING "btree" ("page_id");



CREATE INDEX "idx_page_donations_page_id" ON "public"."page_donations" USING "btree" ("page_id");



CREATE INDEX "idx_page_media_page_id" ON "public"."page_media" USING "btree" ("page_id");



CREATE INDEX "idx_page_widgets_page_id" ON "public"."page_widgets" USING "btree" ("page_id");



CREATE INDEX "idx_pages_created_at" ON "public"."pages" USING "btree" ("created_at");



CREATE INDEX "idx_pages_is_published" ON "public"."pages" USING "btree" ("is_published");



CREATE INDEX "idx_pages_org_type_id" ON "public"."pages" USING "btree" ("organization_type", "organization_id");



CREATE INDEX "idx_prayer_reactions_prayer" ON "public"."prayer_reactions" USING "btree" ("prayer_id");



CREATE INDEX "idx_prayer_updates_prayer" ON "public"."prayer_updates" USING "btree" ("prayer_id");



CREATE INDEX "idx_prayers_page" ON "public"."prayers" USING "btree" ("page_id");



CREATE INDEX "idx_prayers_published" ON "public"."prayers" USING "btree" ("is_published", "visibility");



CREATE INDEX "idx_prayers_user" ON "public"."prayers" USING "btree" ("user_id");



CREATE OR REPLACE TRIGGER "trg_prayers_updated_at" BEFORE UPDATE ON "public"."prayers" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



CREATE OR REPLACE TRIGGER "trg_react_count_del" AFTER DELETE ON "public"."prayer_reactions" FOR EACH ROW EXECUTE FUNCTION "public"."bump_amen_count"();



CREATE OR REPLACE TRIGGER "trg_react_count_ins" AFTER INSERT ON "public"."prayer_reactions" FOR EACH ROW EXECUTE FUNCTION "public"."bump_amen_count"();



CREATE OR REPLACE TRIGGER "trg_updates_count_del" AFTER DELETE ON "public"."prayer_updates" FOR EACH ROW EXECUTE FUNCTION "public"."bump_update_count"();



CREATE OR REPLACE TRIGGER "trg_updates_count_ins" AFTER INSERT ON "public"."prayer_updates" FOR EACH ROW EXECUTE FUNCTION "public"."bump_update_count"();



ALTER TABLE ONLY "public"."agencies"
    ADD CONSTRAINT "agencies_contact_user_id_fkey" FOREIGN KEY ("contact_user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."churches"
    ADD CONSTRAINT "churches_contact_user_id_fkey" FOREIGN KEY ("contact_user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."colleges"
    ADD CONSTRAINT "colleges_contact_user_id_fkey" FOREIGN KEY ("contact_user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."donors"
    ADD CONSTRAINT "donors_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."missionaries"
    ADD CONSTRAINT "missionaries_agency_id_fkey" FOREIGN KEY ("agency_id") REFERENCES "public"."agencies"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."missionaries"
    ADD CONSTRAINT "missionaries_college_id_fkey" FOREIGN KEY ("college_id") REFERENCES "public"."colleges"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."missionaries"
    ADD CONSTRAINT "missionaries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."page_approvals"
    ADD CONSTRAINT "page_approvals_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."page_approvals"
    ADD CONSTRAINT "page_approvals_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "public"."pages"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."page_approvals"
    ADD CONSTRAINT "page_approvals_requested_by_fkey" FOREIGN KEY ("requested_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."page_donations"
    ADD CONSTRAINT "page_donations_donor_id_fkey" FOREIGN KEY ("donor_id") REFERENCES "public"."donors"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."page_donations"
    ADD CONSTRAINT "page_donations_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "public"."pages"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."page_media"
    ADD CONSTRAINT "page_media_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "public"."pages"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."page_widgets"
    ADD CONSTRAINT "page_widgets_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "public"."pages"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."prayer_reactions"
    ADD CONSTRAINT "prayer_reactions_prayer_id_fkey" FOREIGN KEY ("prayer_id") REFERENCES "public"."prayers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."prayer_reactions"
    ADD CONSTRAINT "prayer_reactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."prayer_updates"
    ADD CONSTRAINT "prayer_updates_prayer_id_fkey" FOREIGN KEY ("prayer_id") REFERENCES "public"."prayers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."prayer_updates"
    ADD CONSTRAINT "prayer_updates_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."prayers"
    ADD CONSTRAINT "prayers_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "public"."pages"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."prayers"
    ADD CONSTRAINT "prayers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_role_fkey" FOREIGN KEY ("role") REFERENCES "public"."user_roles"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



CREATE POLICY "Admins and Managers can access" ON "public"."user_roles" TO "authenticated" USING (("auth"."uid"() IN ( SELECT "users"."user_id"
   FROM "public"."users"
  WHERE ("users"."role" = ANY (ARRAY[1, 2]))))) WITH CHECK (("auth"."uid"() IN ( SELECT "users"."user_id"
   FROM "public"."users"
  WHERE ("users"."role" = ANY (ARRAY[1, 2])))));



CREATE POLICY "Admins and Staff can update all users" ON "public"."users" FOR UPDATE USING (("role" = ANY (ARRAY[1, 2]))) WITH CHECK (("role" = ANY (ARRAY[1, 2])));



CREATE POLICY "Admins and Staff can view all users" ON "public"."users" FOR SELECT USING (("role" = ANY (ARRAY[1, 2])));



CREATE POLICY "All" ON "public"."colleges" TO "authenticated" USING (("auth"."uid"() IN ( SELECT "users"."user_id"
   FROM "public"."users"
  WHERE ("users"."role" = ANY (ARRAY[1, 2]))))) WITH CHECK (("auth"."uid"() IN ( SELECT "users"."user_id"
   FROM "public"."users"
  WHERE ("users"."role" = ANY (ARRAY[1, 2])))));



CREATE POLICY "Auth users can amen published public prayers" ON "public"."prayer_reactions" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."prayers" "p"
  WHERE (("p"."id" = "prayer_reactions"."prayer_id") AND ("p"."is_published" = true) AND ("p"."visibility" = 'public'::"text") AND ("p"."deleted_at" IS NULL)))));



CREATE POLICY "Create Admin" ON "public"."users" FOR INSERT WITH CHECK (("role" = ANY (ARRAY[1, 2])));



CREATE POLICY "Owner can delete prayers" ON "public"."prayers" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Owner can read own prayers" ON "public"."prayers" FOR SELECT TO "authenticated" USING ((("auth"."uid"() = "user_id") AND ("deleted_at" IS NULL)));



CREATE POLICY "Owner can read/create updates on own prayer" ON "public"."prayer_updates" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."prayers" "p"
  WHERE (("p"."id" = "prayer_updates"."prayer_id") AND ("p"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."prayers" "p"
  WHERE (("p"."id" = "prayer_updates"."prayer_id") AND ("p"."user_id" = "auth"."uid"())))));



CREATE POLICY "Owner can update prayers" ON "public"."prayers" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Owner can view their own page" ON "public"."pages" FOR SELECT USING (((("organization_type" = 'missionary'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."missionaries" "m"
  WHERE (("m"."id" = "pages"."organization_id") AND ("m"."user_id" = "auth"."uid"()))))) OR (("organization_type" = 'church'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."churches" "ch"
  WHERE (("ch"."id" = "pages"."organization_id") AND ("ch"."contact_user_id" = "auth"."uid"()))))) OR (("organization_type" = 'college'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."colleges" "co"
  WHERE (("co"."id" = "pages"."organization_id") AND ("co"."contact_user_id" = "auth"."uid"()))))) OR (("organization_type" = 'agency'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."agencies" "ag"
  WHERE (("ag"."id" = "pages"."organization_id") AND ("ag"."contact_user_id" = "auth"."uid"()))))) OR (("organization_type" = 'donor'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."donors" "d"
  WHERE (("d"."id" = "pages"."organization_id") AND ("d"."user_id" = "auth"."uid"())))))));



CREATE POLICY "Owner or org contact can manage page" ON "public"."pages" USING (((("organization_type" = 'missionary'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."missionaries" "m"
  WHERE (("m"."id" = "pages"."organization_id") AND ("m"."user_id" = "auth"."uid"()))))) OR (("organization_type" = 'church'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."churches" "ch"
  WHERE (("ch"."id" = "pages"."organization_id") AND ("ch"."contact_user_id" = "auth"."uid"()))))) OR (("organization_type" = 'college'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."colleges" "co"
  WHERE (("co"."id" = "pages"."organization_id") AND ("co"."contact_user_id" = "auth"."uid"()))))) OR (("organization_type" = 'agency'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."agencies" "ag"
  WHERE (("ag"."id" = "pages"."organization_id") AND ("ag"."contact_user_id" = "auth"."uid"()))))) OR (("organization_type" = 'donor'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."donors" "d"
  WHERE (("d"."id" = "pages"."organization_id") AND ("d"."user_id" = "auth"."uid"())))))));



CREATE POLICY "Public can read published prayers" ON "public"."prayers" FOR SELECT USING ((("is_published" = true) AND ("deleted_at" IS NULL) AND ("visibility" = 'public'::"text")));



CREATE POLICY "Public can read updates of public prayers" ON "public"."prayer_updates" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."prayers" "p"
  WHERE (("p"."id" = "prayer_updates"."prayer_id") AND ("p"."is_published" = true) AND ("p"."visibility" = 'public'::"text") AND ("p"."deleted_at" IS NULL)))));



CREATE POLICY "Public can view media of published pages" ON "public"."page_media" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."pages" "p"
  WHERE (("p"."id" = "page_media"."page_id") AND ("p"."is_published" = true)))));



CREATE POLICY "Public can view published pages" ON "public"."pages" FOR SELECT USING (("is_published" = true));



CREATE POLICY "Public can view widgets of published pages" ON "public"."page_widgets" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."pages" "p"
  WHERE (("p"."id" = "page_widgets"."page_id") AND ("p"."is_published" = true)))));



CREATE POLICY "Public read reactions of public prayers" ON "public"."prayer_reactions" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."prayers" "p"
  WHERE (("p"."id" = "prayer_reactions"."prayer_id") AND ("p"."is_published" = true) AND ("p"."visibility" = 'public'::"text") AND ("p"."deleted_at" IS NULL)))));



CREATE POLICY "Reactor can delete reaction" ON "public"."prayer_reactions" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert prayers" ON "public"."prayers" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."agencies" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "agencies_delete_admin" ON "public"."agencies" FOR DELETE USING ("public"."is_admin"());



CREATE POLICY "agencies_insert_admin" ON "public"."agencies" FOR INSERT WITH CHECK ("public"."is_admin"());



CREATE POLICY "agencies_select_public" ON "public"."agencies" FOR SELECT USING (true);



CREATE POLICY "agencies_update_admin_or_owner" ON "public"."agencies" FOR UPDATE USING (("public"."is_admin"() OR ("contact_user_id" = "auth"."uid"())));



ALTER TABLE "public"."churches" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "churches_delete_admin" ON "public"."churches" FOR DELETE USING ("public"."is_admin"());



CREATE POLICY "churches_insert_admin" ON "public"."churches" FOR INSERT WITH CHECK ("public"."is_admin"());



CREATE POLICY "churches_select_public" ON "public"."churches" FOR SELECT USING (true);



CREATE POLICY "churches_update_admin_or_owner" ON "public"."churches" FOR UPDATE USING (("public"."is_admin"() OR ("contact_user_id" = "auth"."uid"())));



ALTER TABLE "public"."colleges" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "colleges_delete_admin" ON "public"."colleges" FOR DELETE USING ("public"."is_admin"());



CREATE POLICY "colleges_insert_admin" ON "public"."colleges" FOR INSERT WITH CHECK ("public"."is_admin"());



CREATE POLICY "colleges_select_public" ON "public"."colleges" FOR SELECT USING (true);



CREATE POLICY "colleges_update_admin_or_owner" ON "public"."colleges" FOR UPDATE USING (("public"."is_admin"() OR ("contact_user_id" = "auth"."uid"())));



ALTER TABLE "public"."donors" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "donors_delete_admin" ON "public"."donors" FOR DELETE USING ("public"."is_admin"());



CREATE POLICY "donors_insert_admin" ON "public"."donors" FOR INSERT WITH CHECK ("public"."is_admin"());



CREATE POLICY "donors_select_public" ON "public"."donors" FOR SELECT USING (true);



CREATE POLICY "donors_update_admin_or_owner" ON "public"."donors" FOR UPDATE USING (("public"."is_admin"() OR ("user_id" = "auth"."uid"())));



ALTER TABLE "public"."missionaries" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "missionaries_delete_admin" ON "public"."missionaries" FOR DELETE USING ("public"."is_admin"());



CREATE POLICY "missionaries_insert_admin" ON "public"."missionaries" FOR INSERT WITH CHECK ("public"."is_admin"());



CREATE POLICY "missionaries_select_public" ON "public"."missionaries" FOR SELECT USING (true);



CREATE POLICY "missionaries_update_admin_or_owner" ON "public"."missionaries" FOR UPDATE USING (("public"."is_admin"() OR ("user_id" = "auth"."uid"())));



ALTER TABLE "public"."page_approvals" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."page_donations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."page_media" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."page_widgets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."prayer_reactions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."prayer_updates" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."prayers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."bump_amen_count"() TO "anon";
GRANT ALL ON FUNCTION "public"."bump_amen_count"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."bump_amen_count"() TO "service_role";



GRANT ALL ON FUNCTION "public"."bump_update_count"() TO "anon";
GRANT ALL ON FUNCTION "public"."bump_update_count"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."bump_update_count"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."is_admin"() TO "anon";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "service_role";



GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "service_role";


















GRANT ALL ON TABLE "public"."agencies" TO "anon";
GRANT ALL ON TABLE "public"."agencies" TO "authenticated";
GRANT ALL ON TABLE "public"."agencies" TO "service_role";



GRANT ALL ON SEQUENCE "public"."agencies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."agencies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."agencies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."churches" TO "anon";
GRANT ALL ON TABLE "public"."churches" TO "authenticated";
GRANT ALL ON TABLE "public"."churches" TO "service_role";



GRANT ALL ON SEQUENCE "public"."churches_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."churches_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."churches_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."colleges" TO "anon";
GRANT ALL ON TABLE "public"."colleges" TO "authenticated";
GRANT ALL ON TABLE "public"."colleges" TO "service_role";



GRANT ALL ON SEQUENCE "public"."colleges_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."colleges_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."colleges_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."donors" TO "anon";
GRANT ALL ON TABLE "public"."donors" TO "authenticated";
GRANT ALL ON TABLE "public"."donors" TO "service_role";



GRANT ALL ON SEQUENCE "public"."donors_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."donors_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."donors_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."missionaries" TO "anon";
GRANT ALL ON TABLE "public"."missionaries" TO "authenticated";
GRANT ALL ON TABLE "public"."missionaries" TO "service_role";



GRANT ALL ON SEQUENCE "public"."missionaries_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."missionaries_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."missionaries_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."page_approvals" TO "anon";
GRANT ALL ON TABLE "public"."page_approvals" TO "authenticated";
GRANT ALL ON TABLE "public"."page_approvals" TO "service_role";



GRANT ALL ON SEQUENCE "public"."page_approvals_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."page_approvals_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."page_approvals_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."page_donations" TO "anon";
GRANT ALL ON TABLE "public"."page_donations" TO "authenticated";
GRANT ALL ON TABLE "public"."page_donations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."page_donations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."page_donations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."page_donations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."page_media" TO "anon";
GRANT ALL ON TABLE "public"."page_media" TO "authenticated";
GRANT ALL ON TABLE "public"."page_media" TO "service_role";



GRANT ALL ON SEQUENCE "public"."page_media_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."page_media_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."page_media_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."page_widgets" TO "anon";
GRANT ALL ON TABLE "public"."page_widgets" TO "authenticated";
GRANT ALL ON TABLE "public"."page_widgets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."page_widgets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."page_widgets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."page_widgets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pages" TO "anon";
GRANT ALL ON TABLE "public"."pages" TO "authenticated";
GRANT ALL ON TABLE "public"."pages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."prayer_reactions" TO "anon";
GRANT ALL ON TABLE "public"."prayer_reactions" TO "authenticated";
GRANT ALL ON TABLE "public"."prayer_reactions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."prayer_reactions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."prayer_reactions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."prayer_reactions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."prayer_updates" TO "anon";
GRANT ALL ON TABLE "public"."prayer_updates" TO "authenticated";
GRANT ALL ON TABLE "public"."prayer_updates" TO "service_role";



GRANT ALL ON SEQUENCE "public"."prayer_updates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."prayer_updates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."prayer_updates_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."prayers" TO "anon";
GRANT ALL ON TABLE "public"."prayers" TO "authenticated";
GRANT ALL ON TABLE "public"."prayers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."prayers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."prayers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."prayers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_roles" TO "anon";
GRANT ALL ON TABLE "public"."user_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."user_roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_roles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































