#!/usr/bin/env bash
set -euo pipefail

# =============================================================
# Generate supabase/seed.sql from a live DB
#
# Extracts data from configurable tables and wraps each INSERT
# with idempotent ON CONFLICT / NOT EXISTS guards so the seed
# can be re-run safely.
#
# Usage:
#   DB_URL=postgres://... ./scripts/generate-seed.sh
#   ./scripts/generate-seed.sh --db-url "postgres://..."
#   ./scripts/generate-seed.sh --limit 5          # max rows per table
#   ./scripts/generate-seed.sh --anonymize        # redact emails/names
# =============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_FILE="$PROJECT_ROOT/supabase/seed.sql"

DB_URL="${DB_URL:-}"
LIMIT=10
ANONYMIZE=0

TABLES=(
  "public.user_roles"
  "public.churches"
  "public.agencies"
  "public.colleges"
  "public.missionaries"
  "public.pages"
  "public.missionary_churches"
)

while [[ $# -gt 0 ]]; do
  case "$1" in
    --db-url)     DB_URL="$2"; shift 2 ;;
    --limit)      LIMIT="$2"; shift 2 ;;
    --anonymize)  ANONYMIZE=1; shift ;;
    -h|--help)    sed -n '3,15p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$DB_URL" ]]; then
  echo "ERROR: DB_URL not set. Pass via env or --db-url." >&2
  exit 1
fi

if ! command -v pg_dump >/dev/null 2>&1; then
  echo "ERROR: pg_dump not found. Install libpq: brew install libpq" >&2
  exit 1
fi

echo "==> Generating $OUT_FILE"
echo "==> Tables: ${TABLES[*]}"
echo "==> Limit per table: $LIMIT"

{
  echo "-- AUTO-GENERATED by scripts/generate-seed.sh"
  echo "-- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "-- Source: linked Supabase DB (public schema)"
  echo "-- Note: schema assumes tables exist via migrations. Idempotent."
  echo
  echo "BEGIN;"
  echo "SET session_replication_role = 'replica';  -- bypass FK/triggers"
  echo
} > "$OUT_FILE"

TABLE_ARGS=()
for t in "${TABLES[@]}"; do
  TABLE_ARGS+=("--table=$t")
done

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

pg_dump "$DB_URL" \
  --data-only \
  --column-inserts \
  --no-owner --no-privileges \
  "${TABLE_ARGS[@]}" \
  > "$TMP"

if [[ "$ANONYMIZE" -eq 1 ]]; then
  sed -i.bak -E \
    -e "s/('[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})/\\\\xxxx@example.com/g" \
    "$TMP"
  rm -f "$TMP.bak"
fi

grep -E '^INSERT INTO' "$TMP" \
  | sed 's/;$/ ON CONFLICT DO NOTHING;/' \
  >> "$OUT_FILE"

{
  echo
  echo "-- Reset IDENTITY sequences past seeded rows"
  for t in "${TABLES[@]}"; do
    tbl="${t#public.}"
    echo "SELECT setval(pg_get_serial_sequence('$t','id'), COALESCE((SELECT MAX(id) FROM $t), 1));"
  done
  echo
  echo "SET session_replication_role = 'origin';"
  echo "COMMIT;"
} >> "$OUT_FILE"

LINE_COUNT=$(wc -l < "$OUT_FILE" | tr -d ' ')
echo "==> Wrote $OUT_FILE ($LINE_COUNT lines)"
echo "==> Review before committing:"
echo "     head -20 $OUT_FILE"
